#!/bin/bash

BOOT_HEIGHT=10
BOOT_WIDTH=54
BOOT_CHOICE_HEIGHT=8
BACKTITLE="*** DOSBIAN CUSTOMIZATION - Developed by Carmelo Maiolino (C) 2020 *** "
BOOT_TITLE="PRESS OK TO PROCEED OR ESC TO ABORT"
dialog --title "$BOOT_TITLE" --backtitle "$BACKTITLE" --msgbox "\nPlease, insert a USB key containing in the root a file named 'splash.jpg'.\n\nOnce done, press OK or ESC to Abort " 12 60 
if [ $? -ne 0 ]; then
   clear;
   exit;
fi;
if [ -f "/media/usb0/splash.jpg" ]; then
   sudo cp yes | /media/usb0/splash.jpg /usr/local/bin/.
   dialog --clear --title "$BOOT_TITLE" --backtitle "$BACKTITLE" --msgbox "\nOperation completed. If you followed the instructions correcty, your splash screen will appear at next boot. " 12 60 
else
   dialog --clear --title "$BOOT_TITLE" --backtitle "$BACKTITLE" --msgbox "\nOperation aborted!\n\nThe file 'splash.jpg' was not found in your USB key. " 12 60 
fi;







