#!/bin/bash

EDIT_HEIGHT=10
EDIT_WIDTH=54
EDIT_CHOICE_HEIGHT=8
BACKTITLE="*** DOSBIAN CUSTOMIZATION - Developed by Carmelo Maiolino (C) 2020 *** "
EDIT_TITLE="CHOOSE WHAT TO CUSTOMIZE"

EDIT_OPTIONS=(
        "" ""
        1 " CHANGE BOOT LOGO"
	2 " ENABLE/DISABLE BEEP AT BOOT  "
	"" ""
)






function customize_menu
{
	while :
	do

		choice=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$EDIT_TITLE" \
		--menu "" \
                $EDIT_HEIGHT $EDIT_WIDTH $EDIT_CHOICE_HEIGHT \
                "${EDIT_OPTIONS[@]}" \
                2>&1 >/dev/tty)

		if [ $? -ne 0 ]; then
			clear;
			exit;
		fi;

		clear

		case $choice in

			1)  sudo change_boot
	    		    break
            		    ;;

			2) beeper
            		   break 
	    		    ;;

		esac
	done
}




customize_menu



