#!/bin/bash

printf "DOSBIAN is checking for updates, Please wait..."
sudo wget -q --spider https://google.com

if [ $? -eq 0 ]; then
	# Internet connection detected,  connecting ...

	printf "\n\nBACKINGUP FILES..."
	cp -a /usr/local/bin/.  /root/backup

	printf "\n\nUPDATING FILES..."
	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/configrestore -O /usr/local/bin/configrestore
	sudo chmod -R 777 /usr/local/bin/configrestore

	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/dosbianupdate -O /usr/local/bin/dosbianupdate
	sudo chmod -R 777 /usr/local/bin/dosbianupdate

	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/imagemount -O /usr/local/bin/imagemount
	sudo chmod -R 777 /usr/local/bin/imagemount

	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/info -O /usr/local/bin/info
	sudo chmod -R 777 /usr/local/bin/info

	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/ipxboxconfig -O /usr/local/bin/ipxboxconfig
	sudo chmod -R 777 /usr/local/bin/ipxboxconfig

	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/mediacreator -O /usr/local/bin/mediacreator
	sudo chmod -R 777 /usr/local/bin/mediacreator

	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/menu -O /usr/local/bin/menu
	sudo chmod -R 777 /usr/local/bin/menu

	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/menuconfigurator -O /usr/local/bin/menuconfigurator
	sudo chmod -R 777 /usr/local/bin/menuconfigurator

	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/menumedia -O /usr/local/bin/menumedia
	sudo chmod -R 777 /usr/local/bin/menumedia

	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/mountdrive -O /usr/local/bin/mountdrive
	sudo chmod -R 777 /usr/local/bin/mountdrive

	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/unmountdrive -O /usr/local/bin/unmountdrive
	sudo chmod -R 777 /usr/local/bin/unmountdrive

	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/beeper -O /usr/local/bin/beeper
	sudo chmod -R 777 /usr/local/bin/beeper

	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/change_boot -O /usr/local/bin/change_boot
	sudo chmod -R 777 /usr/local/bin/change_boot

	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/customize -O /usr/local/bin/customize
	sudo chmod -R 777 /usr/local/bin/customize


	printf "\n\nUPDATING IMAGES..."
	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/dosbianmenu.jpg -O /usr/local/bin/dosbianmenu.jpg
	sudo chmod -R 777 /usr/local/bin/dosbianmenu.jpg

	sudo wget -N -q https://raw.githubusercontent.com/appnjoy/dosbian/master/v15/splash.jpg -O /usr/local/bin/splash.jpg
	sudo chmod -R 777 /usr/local/bin/splash.jpg

	printf "\n\nDOSBIAN WAS SUCCESSFULL UPDATED!"

	printf "\n\nTo enable all the changes, a reboot is required.\n\n"
	printf "PLEASE NOTE: If the update corrupted your system, no panic!, from console, type the command: sudo dosbianrestore\n\n"	
	read -n 1 -s -r -p "Press any key to REBOOT "

	printf "\n\nREBOOTING... "
	sudo reboot now

else

	printf "\n\nSorry, no internet connection detected, OPERATION ABORTED.\n\n"
	read -n 1 -s -r -p "Press any key to get back to Dosbian menu " 

fi



